### ISSUE TITLE
Publish new release?

### ISSUE THREAD

**Issue by repi** [davidpdrsn/extend#10]
Possible to publish a new version on crates.io? 

Specifically after #9 to get rid of old pre-1.0 `proc-macro-error` and `proc-macro-error-attr` crates.

**Comment by davidpdrsn** [comment]
Oh yeah sorry I forgot. I’ll publish a new release tomorrow.

**Comment by davidpdrsn** [comment]
I just published version 0.1.2

**Comment by repi** [comment]
Thanks!
