### ISSUE TITLE
Extensions with multiple generic params don't work

### ISSUE THREAD

**Issue by davidpdrsn** [davidpdrsn/extend#11]
An extension like this

```rust
struct Foo<T>(PhantomData<T>);

#[ext]
impl<T, K> T {
    fn some_method(&self, _: Foo<K>) {}
}
```

Gives an `unconstrained type parameter` error. This is because the trait generated to make the extension trait sealed looks like:

```rust
mod private_TExt {
    use super::*;
    pub trait Sealed {}
    impl<T, K> Sealed for T {}
         // ^ K is unconstrained
}
```

Fixing this leads to problems mentioned [here](https://github.com/davidpdrsn/extend/issues/7#issuecomment-633120661).

I think a reasonable fix is to simply not make the generated traits sealed. I don't think there is much value in sealing them anyway.

**Comment by Boscop** [comment]
@davidpdrsn Btw, is the `#[inline(always)]` applied on the method impl or on the method declaration in this case? 
(It has no effect on the method declaration, it must be on the method impl.)
```rust
#[ext(pub, name = RangeWithLen)]
impl<T: Copy + Add<Output = T>> T {
	#[inline(always)]
	fn range_with_len(self, len: T) -> Range<T> {
		self .. self + len
	}
}
```

**Comment by davidpdrsn** [comment]
All attributes are applied in both places, so both in the trait definition and on the impl.
