### ISSUE TITLE
Please support associated types

### ISSUE THREAD

**Issue by ijackson** [davidpdrsn/extend#17]
It might seem that these are not needed.  But they are, if any of the extension methods returns an unnameable type.  In that case in a crate with `#![feature(type_alias_impl_trait)]` it is possible to specify the associated type as `impl ...`  Except that that means not using `#[ext]` which is a shame.

FTR, here is the code I would like to work (roughly speaking):

```
#[ext(pub)]
impl< I: Iterator,
      U,
      F: FnMut(I::Item) -> Result<U,Loop>,
    > I
{
  type Return = impl Iterator<Item=U>;

  fn map_loop(self, f: F) -> Return {
    self
      .map(f)
      .filter(|i| !matches!(i, Err(Loop::Continue)))
      .take_while(|i| !matches!(i, Err(Loop::Break)))
      .map(|i| i.ok().unwrap())
  }
```

Now I could write `impl ...` for the return value but that even-more-generalised type inference doesn't seem likely to be stablised any time soon.

**Comment by davidpdrsn** [comment]
I have personally never played with `type_alias_impl_trait`. Does this have any use cases outside of `type_alias_impl_trait` and `type Foo = impl ...`? I would rather not add features that are only useful when using unstable features.

**Comment by ijackson** [comment]
Thanks for your attention.

>  Does this have any use cases outside of `type_alias_impl_trait` and `type Foo = impl ...`?

None occurs to me.

> I would rather not add features that are only useful when using unstable features.

That makes sense.  OK, thanks.  I will close this.  I may come back ot you if `type_alias_impl_trait` gets stabilised...
