### ISSUE TITLE
Rust-analyzer does not recognize Imports of extension traits

### ISSUE THREAD

**Issue by elkowar** [davidpdrsn/extend#18]
When using extend, importing extension-traits made with this macro are not recognized by rust-analyzer.
I'm not all that familiar with how exactly this works and what would need to be done to fix this, but having a ton of `unrecognized import` errors while working is more than distracting. Seeing that other proc-macro based crates that create public stuff that _is_ importable _do_ work, i'd assume this is possible?

**Comment by davidpdrsn** [comment]
I have noticed this as well but its most certainly a bug in rust-analyzer. `cargo build` has no problems. Care to file an issue for rust-analyzer instead?

**Comment by SrTobi** [comment]
Have the same problem. I opened an issue here: https://github.com/rust-analyzer/rust-analyzer/issues/8219
For the time being I suggest using `*` imports... not great, not terrible

**Comment by davidpdrsn** [comment]
Rust analyzer issue: https://github.com/rust-analyzer/rust-analyzer/issues/6029
