### ISSUE TITLE
How to derive the extension trait from other trait?

### ISSUE THREAD

**Issue by Boscop** [davidpdrsn/extend#3]
How to derive the extension trait from other trait, is it supported? 
If not, it would be very useful to add..

**Comment by davidpdrsn** [comment]
You mean like this?

```rust
use std::fmt::Display;

#[ext]
impl<T: Display> T {
    fn display(&self) -> String {
        format!("{}", self)
    }
}

fn main() {
    let s = "foo".to_string();

    s.display();
}
```

**Comment by Boscop** [comment]
I mean the generated trait should be a sub-trait to a given trait (or multiple, joined with +).
I often need this with e.g. `Default` etc.

**Comment by Boscop** [comment]
@davidpdrsn That would generate `impl<T: Display> GeneratedTrait for T {`, right?
I would like to express `trait GeneratedTrait: SuperTrait { ..`. 
I often need to make the generated trait a sub-trait.
This is orthogonal to the `<T: Trait>` bound. Ideally, both should be possible together..

**Comment by davidpdrsn** [comment]
Ah I see. No that isn’t possible. I have personally never written an extension trait like that. Do you have an example use case?

**Comment by Boscop** [comment]
@davidpdrsn Yes, in several cases where I need the generated trait to derive from `Default`, `DynClone` or `TypeName + Serialize + DeserializeOwned`. It comes up quite often actually..
